name: CICD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [8]
    steps:
      - name: Checkout Code
        uses: ./.github/actions/checkout.yml

      - name: Setup Node.js
        uses: ./.github/actions/setup-node.yml
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm and Cache
        uses: ./.github/actions/setup-pnpm.yml
        with:
          pnpm-version: ${{ matrix.pnpm-version }}

      - name: Install Playwright and Dependencies
        uses: ./.github/actions/install-deps.yml

      - name: Run NX Affected Commands
        uses: ./.github/actions/run-affected.yml

      - name: Publish Packages
        if: github.event_name == 'push'
        uses: ./.github/actions/publish.yml
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
